logging:
  level:
    org.springframework.web: DEBUG

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_chain?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    content-type: text/html
    cache: false
    mode: LEGACYHTML5


server:
  url: http://localhost:8888
  port: 81
  tomcat:
    max-threads: 900
    uri-encoding: utf-8


mybatis:
  typeAliasesPackage: org.spring.springboot.domain
  mapperLocations: classpath:mapper/*.xml
